services:
  postgres:
    build:
      context: ..
      dockerfile: deployments/postgres/Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT_INCREMENTED}:${POSTGRES_PORT}"
    volumes:
      - albums-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  init-postgres:
    image: postgres:13-alpine
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD}
    entrypoint: [ "/bin/sh", "-c" ]
    command: |
      "
      psql -h postgres -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f /migrations/ddl.sql
      psql -h postgres -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f /migrations/dml.sql
      psql -h postgres -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f /migrations/dal.sql
      "
    volumes:
      - ../migrations:/migrations

  authorization:
    build:
      context: ..
      dockerfile: deployments/go/Dockerfile
      args:
        SERVICE_NAME: authorization
        SERVICE_PORT: ${AUTHORIZATION_PORT}
    ports:
      - "${AUTHORIZATION_PORT}:${AUTHORIZATION_PORT}"
    depends_on:
      postgres: 
        condition: service_healthy
    init: true

  profile:
    build:
      context: ..
      dockerfile: deployments/go/Dockerfile
      args:
        SERVICE_NAME: profile
        SERVICE_PORT: ${PROFILE_PORT}
    ports:
      - "${PROFILE_PORT}:${PROFILE_PORT}"
    depends_on:
      postgres: 
        condition: service_healthy
    init: true

  gateway:
    build:
      context: ..
      dockerfile: deployments/go/Dockerfile
      args:
        SERVICE_NAME: gateway
        SERVICE_PORT: ${GATEWAY_PORT}
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    depends_on:
      - authorization
      - postgres
    init: true
    
volumes:
  albums-data: